### ISSUE TITLE
technical task (alpha)

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#1]
Курсовая работа: Биржа грузоперевозок
Одновременно помогает как заказчику с поиском лучшего предложения на перевозку его груза, так и исполнителю с поиском возможных заказов. 
Заказчик создает заявку на грузоперевозку (масса, маршрут, предполагаемая цена, дата, фото, описание и тд). Заявку одобряет администратор. Исполнители видят заявки которые оставили пользователи и могут на них откликаться своим предложением (комментарий, цена).  Заказчик видит все предложения полученные от исполнителей и среди них выбирает то, которое его устраивает, тогда исполнителю приходит уведомление о том, что его предложение приняли и он может его выполнять. По выполнении работы заказчику будет предложено поставить исполнителю оценку и написать отзыв. 
Вход осуществляется при помощи логина и пароля. Всего существует 3 типа пользователей: заказчик, исполнитель и администратор.

**Comment by wldmr-key** [comment]
Норм. Принимается. Напрашивается предоставление анализа для исполнителей (и, возможно, заказчиков) по принятым/отвергнутым заказам (иначе история заказов остается практически невостребованной)
