### ISSUE TITLE
Оформление проектно-конструкторской части

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#11]

**Comment by innocentzy** [comment]
3.1. Разработка алгоритмов обработки информации
Алгоритм подключения базы данных к программе в settings.py:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
Алгоритм вывода данных из БД по запросу пользователя. Например, пользователь зашел в “Мои заявки”, чтобы увидеть свои заявки и ответы на них. Мы создаем в классе ApplicationView функцию def get_context_data(self, **kwargs): и описываем, что должна вернуть эта функция. Сортируем заказы по дате создания заказа kwargs['apps'] = Application.objects.order_by('-vip', '-createDate'). И возвращаем через return super().get_context_data(**kwargs).
Алгоритм добавления новой заявки в таблицу заявок. Пользователь заходит в “Мои заявки” и нажимает кнопку “Создать”, заполняет форму и запускается алгоритм добавления новой заявки в таблицу заявок через функцию def form_valid(self, form):. В данной функции к БД отправляется запрос на добавление строки с заявкой, далее в поле author присваивается имя пользователя,  далее производится проверка и данные сохраняются.
Алгоритм добавления ответа на заявку. Пользователь заходит на заявку на которую он хочет ответить и нажимает кнопку “Ответить на заявку”, после заполнения формы запускается алгоритм добавления нового ответа в таблицу через функцию def create_answer(request, pk): В данной функции к БД отправляется запрос на добавление строки с ответом и строка появляется в таблице.

3.2	Логическая схема базы данных
   
Рисунок 4. Логическая схема базы данных

3.3. Реализация архитектуры приложения.
Приложение является веб-сайтом биржи грузоперевозок, разработанным на основе фреймворка Django. Для удобства пользователей реализовано интуитивно понятное меню и интерфейс пользователя. На сайте реализована работа с базой данных для хранения информации о грузах и перевозках.
Для разработки использовалась среда PyCharm, а язык программирования - Python. В качестве СУБД была выбрана SQLite, так как она легка в использовании и хранении информации малого объема. Приложение разрабатывалось для кроссплатформенного доступа к бирже грузоперевозок через веб-интерфейс, что позволяет ему работать на любой ОС..
3.4. Разработка графического интерфейса взаимодействия пользователя с системой.
Приложение будет строиться основываясь на шаблоне MVC. MVC - это схема использования нескольких шаблонов, с помощью которых модель данных приложения, пользовательский интерфейс взаимодействие с пользователем разделены на три отдельных компонента так, что модификация одного из компонентов оказывает минимальное воздействие на остальные. Основой проекта будут manage.py, __init__.py, settings.py, urls.py, wsgi.py. 
•	manage.py скрипт, который позволяет вам взаимодействовать с проектом Django.        
•	__init__.py пустой файл, который указывает Python, что текущий каталог является пакетом Python.        
•	settings.py настройки/конфигурация проекта. 
•	urls.py конфигурация URL-ов для вашего проекта Django. Это "содержимое” всех Django-сайтов.       
•	wsgi.py точки входа для WSGI-совместимый веб-серверов.
Графический интерфейс реализован с помощью стандартизированного языка гипертекстовой разметки HTML и каскадных таблиц стилей CSS, что позволило создать интуитивно понятный и привлекательный пользовательский интерфейс для нашего веб-сайта биржи грузоперевозок. Для разработки использовались современные фреймворки и библиотеки, такие как Bootstrap, что обеспечило высокую скорость и удобство работы с элементами интерфейса.
Python Django позволяет смешивать программный код непосредственно с HTML-кодом. Система шаблонов Django предоставляет теги, функции которых аналогичны некоторым программным структурам (тег if для логических тестов, тег for для циклов и т. Д.)
К примеру так реализована основа сайта (based.html): 
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">

</head>
<body>
    <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">

           <b class="fs-3 px-4">GRAND WAY</b>
      </a>
        {% if user.is_superuser %}
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/user" class="nav-link px-4 link-dark fs-5">Личный кабинет</a></li>
      </ul>
      <div class="col-md-3 text-end">
        <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">Выход</button></a>
      </div>
        {% else %}
      {% if user.is_authenticated %}
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/user" class="nav-link px-4 link-dark fs-5">Личный кабинет</a></li>
        <li><a href="/applications" class="nav-link px-4 link-dark fs-5">Мои заявки</a></li>
      </ul>
      <div class="col-md-3 text-end">
        <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">Выход</button></a>
      </div>
      {% else %}
      <div class="col-md-3 text-end">
        <a href="/accounts/login"><button type="button" class="btn btn-outline-primary me-2">Вход</button></a>
        <a href="/accounts/signup"><button type="button" class="btn btn-primary">Регистрация</button></a>
      </div>
      {% endif %}
        {% endif %}
    </header>
  </div>
    <div>
        {% block content %}

        {% endblock %}
    </div>
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/about" class="nav-link px-2 text-muted">О проекте</a></li>
    </ul>
  </footer>
</div>
</body>
</html>

{% block title %} – отвечает за заголовок страницы.
{% endblock %} – закрывает блок заголовка страницы.
{% if user.is_superuser %} – проверка является ли пользователь администратором.
{% if user.is_authenticated %} – проверка является авторизирован ли пользователь.
{% endif %} – закрывает блок проверки.
{% block content %} – блок который в будущем будет заполняться контентом.
3.5. Реализация функционирующего приложения
Описание сущностей базы данных: 
‘User’ – сущность для списка пользователей. Имеет поля:
•	id – [PK] integer, not null
•	name – character varying(255), not null
•	status – bool, not null
•	last_seen – date, not null
‘Application’ – сущность для списка заявок. Имеет поля:
•	id – [PK] integer, not null
•	author - [FK] user, not null
•	title – character varying(255), not null
•	startAddress  –  character varying(255), not null
•	finishAddress – character varying(255), not null
•	text – character varying(255), not null
•	needDate – date, not null
•	status – bool, not null
•	createDate – autodate, not null
‘Answer’ – сущность для списка ответов на заявки. Имеет поля:
•	id – [PK] integer, not null
•	appId – [FK] application, not null
•	author – [FK] user, not null
•	money – positive integer, not null
•	createDate – autodate, not null

**Comment by innocentzy** [comment]
![image](https://user-images.githubusercontent.com/52624927/227619004-cf96978a-dfaa-44a0-a157-ada9ef2cf056.png)

**Comment by wldmr-key** [comment]
почему в логической схеме внезапно уменьшилось количество атрибутов? Как насчет внешних ключей? не?
переделать

**Comment by wldmr-key** [comment]
связи неправильные, внешних ключей по-прежнему нет. На мой взгляд, ты выбрал неудобный для себя же формат Чена

**Comment by innocentzy** [comment]
Могу ли я это заменить на такое?
![схема](https://user-images.githubusercontent.com/52624927/228050440-d9e1d024-97de-42f5-960e-3dca849a9428.png)

**Comment by wldmr-key** [comment]
если связь между заявкой и ответом правильно нарисуешь, то вполне ))

**Comment by innocentzy** [comment]
![схема](https://user-images.githubusercontent.com/52624927/228071251-81007039-3dcb-4c4f-8cca-def1812f6fd4.png)

**Comment by wldmr-key** [comment]
ура
