### ISSUE TITLE
Разработка эксплуатационной документации и/или других компонент технологической части

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#12]

**Comment by innocentzy** [comment]
4. Проектно-технологическая часть
4.1. Проектирование начального и тестового наполнения базы данных. Процедуры автоматизации.
Класс добавления нового пользователя:
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'type')
Класс добавления новой заявки в таблицу application:
class AppCreateView(LoginRequiredMixin, CreateView):
    model = Application
    template_name = 'applications/create.html'
    form_class = ApplicationForm
    success_url = reverse_lazy('apphome')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object = form.save()
        return super().form_valid(form)

Функция добавления нового ответа на заявку в таблицу answers:
def create_answer(request, pk):
    error = ''
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        form.data._mutable = True
        form.data['appId'] = pk
        form.data['author'] = request.user
        form.data._mutable = False
        if form.is_valid():
            form.save()
            print(form.data['appId'])
            return redirect('app-detail', pk)
        else:
            error = 'Неверно заполнена форма!'
    form = AnswerForm()
    data = {
        'form': form,
        'error': error,
        'pk': pk
    }
    return render(request, 'applications/create_answer.html', data)

Данная автоматизация упростит тестовое заполнение базы данных, а так-же ее актуализацию без прямого взаимодействия с СУБД.
Так же имеется возможность прямого добавления информации в базу данных SQLite на сервере через панель администратора.
4.2. Порядок развёртывания системы.
Данное приложение было развернуто в PyCharm.
 
Рисунок 5. Окно PyCharm.
Но перед этим совершаем все действия с созданием проекта, установок модулей, созданием виртуальной среды.
1.	Создаем виртуальную среду, устанавливаем необходимые модули Python для дальнейшей работы: 
python -m pip install Django
 
2.	Подключаем свою БД
 
Рисунок 5. Окно PyCharm.
3.	Запуск приложения
  
Рисунок 6. Окно PyCharm.
4.3 Разработка руководства пользователя и руководства администратора.

Руководство пользователя: 
1.	Для авторизации или регистрации пользователь должен нажать на кнопку “Вход” или “Регистрация” соответственно. 
 
 
Рисунок 7. Главная страница веб-приложения.
2.	Пользователь авторизируется или регистрируется и авторизируется на странице логина.
 
Рисунок 8. Страница авторизации.
 
3. После авторизации, пользователь попадает в вкладку заявок.
 
Рисунок 9. Вкладка “Мои заявки”.

4.	Для создания новой заявки нужно нажать на кнопку “Создать заявку”. 
5.	Пользователь попадает в форму создания заявки.
 
Рисунок 10. Форма создания заявки.
 

6.	Созданная заявка появится во вкладке “Мои заявки”.
 
Рисунок 11. Вкладка “Мои заявки” с новой созданной заявкой.

7.	Для ответа на заявку войдем под аккаунтом грузоперевозчика и войдем в ранее созданную заявку.
 
Рисунок 12. Раннее созданная заявка и предложения водителей.
 
8.	 Для ответа на заявку пользователь должен нажать кнопку “Ответить на заявку” и заполнить форму ответа на заявку.
 
Рисунок 13. Форма ответа на заявку.
9.	 После создания ответа на заявку, пользователь создавший эту заявку увидит новый ответ.
 
Рисунок 14. Заявка с предложением водителя.
10.	 Далее грузовладелец либо соглашается с предложением, либо его отклоняет. При отклонении предложение удаляется, при принятии грузовладелец получает контакты перевозчика и возможность отправить ему сообщение.
Руководство администратора:
1.	Для входа в панель администратора администратор имеет специальный аккаунт. Для проверки или изменении заявок и ответов, администратор имеет доступ к созданным заявкам и ответам в его личном кабинете.
 
Рисунок 15. Личный кабинет администратора.

**Comment by innocentzy** [comment]
![image](https://user-images.githubusercontent.com/52624927/227621819-e035d249-23bc-4d0a-aab9-2533d7f8f276.png)
![image](https://user-images.githubusercontent.com/52624927/227621854-ffdc9b8d-6def-41a5-91c9-0540ccf3aee9.png)
![image](https://user-images.githubusercontent.com/52624927/227621918-2ea91a0f-5b1e-4eb9-81b3-3780be392e0e.png)

**Comment by wldmr-key** [comment]
пойдет
