### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#3]

**Comment by innocentzy** [comment]
Основная часть
1.Техническое задание
1.1 Общие сведения.
1.1.1 Полное наименование системы и ее условное обозначение.
Данное техническое задание регулирует разработку системы торговой площадки (биржи), предназначенной для взаимного контакта между перевозчиком и грузовладельцем для согласования перевозки груза.
1.1.2 Шифр темы или шифр (номер) договора.
Шифры темы или договора отсутствуют.  
1.1.3 Наименование предприятий (объединений) разработчика и заказчика (пользователя) системы и их реквизиты.
Высшее учебное заведение Калужский филиал МГТУ имени Н. Э. Баумана 
1.1.4 Перечень документов, на основании которых создается система, кем и когда утверждены эти документы.
	На основании учебного плана кафедры ИУК5. 
1.1.5 Плановые сроки начала и окончания работы по созданию системы.
	Начало работы: 05.09.2022 
	Окончание работы: 12.12.2022
1.1.6. Сведения об источниках и порядке финансирования работ.
	Финансирование работы отсутствует.	
1.1.7. Порядок оформления и предъявления заказчику результатов работ.
Работы по созданию биржи сдаются Разработчиком поэтапно в соответствии с календарным планом Проекта. По окончании каждого из этапов работ Разработчик сдает Заказчику соответствующие отчетные документы этапа.
1.2. Назначение и цели создания (развития) системы.
1.2.1 Назначение системы.
	Система предназначена для сокращения времени поиска перевозчика для грузовладельцев и повышения эффективности использования транспорта перевозчиков.
1.2.2 Цели создания системы.
Система создается с целью получения прибыли посредством подписок.
1.3. Характеристика объектов автоматизации.
Объектом автоматизации являются процессы по взаимному поиску и сделки о транспортировке груза между перевозчиком и грузовладельцем.
В настоящее время процессы поиска и сделки происходят следующим образом:
- Грузовладелец создает заявку на грузоперевозку.
- Заявка одобряется администратором.
- Перевозчики видят одобренные заявки и могут откликаться на них своими предложениями. 
-  Грузовладелец видит предложения полученные от перевозчиков и выбирает среди них то, которое его устраивает.
- Перевозчик получает уведомление о том, что его предложение приняли и он может начать выполнять заказ.
- По выполнении работы грузовладельцу будет предложено оценить работу перевозчика и написать отзыв.
Сведения о пользователях системы:
•	Грузовладелец
Оставляет заказ на перевозку. В заказ входят данные о массе груза, место загрузки, место разгрузки, цена, дата. 
•	Перевозчик
Просмотр созданных заказов и возможность откликнуться на них своим предложением. Предложение включает в себя цену и тип транспорта. К предложению также добавляется информация о перевозчике: имя, фотография, стаж, рейтинг, транспорт. 
1.4. Требования к системе.
1.4.1. Требования структуре и функционированию системы.
Основным режимом функционирования системы является нормальный режим функционирования. В случае возникновения аварийных ситуаций (отсутствие связи с БД, разрушение БД) необходимо предусмотреть восстановление нормального режима функционирования в срок, не превышающий 1 суток.
Система должна разрабатываться, как система открытого типа, что решает следующие задачи: - обеспечение расширяемости и масштабируемости системы; - повышение качества компонентов системы; - обеспечение переносимости программного обеспечения;
1.4.2. Требования  к численности и квалификации персонала системы.
Квалификации пользователя не требуется. 

1.4.3. Требования к прикладным программам.
Для работы программного комплекса необходимы: 
1.	Тип ОС должен принадлежать семейству Microsoft Windows;
2.	минимальный набор драйверов, обеспечивающих 
работоспособность ПК.

1.4.4. Требования к надежности.
Программа не должна прекращать работу, если это не требуется специалисту или не предусмотрено сценарием использования программы.
1.4.5. Требования к эргономике и технической эстетике.
	Интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых неочевидно или элементы, функционал которых отсутствует или не соответствует пояснению в конструкторской документации или непосредственно в интерфейсе. 
Интерфейс должен быть понятен и не перегружен графическими элементами.
1.4.6. Требования к составу технических средств.
Для функционирования системы необходимы: 
	монитор;
	клавиатура;
	мышь.
1.5. Состав и содержание работ по создание системы
1. Создание прототипа интерфейса. Экспертиза: согласование прототипа с заказчиком.  (Срок 4 неделя)
3. Разработка физической и логической схемы программы. Экспертиза: демонстрация проделанной работы заказчику. (Срок 7 неделя)
4. Разработка макета программы. Экспертиза: демонстрация проделанной работы заказчику. (Срок 10 неделя)
5. Отладка и устранение ошибок программы. Экспертиза: демонстрация проделанной работы заказчику. (Срок 14 неделя)

1.6. Порядок контроля и приемки системы.
1.6.1 Общие требования к приемке работ по стадиям
	1 – 4-я неделя: Выбор и согласование темы с руководителем; проведение исследования по выбранной теме, обзор существующих программных продуктов; разработка технического задания. Выбор и согласование темы с руководителем; проведение исследования по выбранной теме, обзор существующих программных продуктов; разработка технического задания.
	5 – 7-я недели: Разработка и реализация алгоритмов функционирования приложения, структуры, систем передачи информации, технологий обработки информации и интерфейса взаимодействия пользователя с системой. Выполнение и оформление проектно-конструкторской части работы.
	9 – 10-я недели: Тестирование и отладка программного приложения. Разработка руководства пользователя и программиста. Написание проектно-технологической части расчетно-пояснительной записки.
	11 – 14-я недели: Завершающее оформление документации согласно требованиям, ГОСТ и данного методического пособия. Подготовка доклада. Защита курсовой работы.

1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие 
	Коррекции и разрешение к показу программы приёмной комиссии является научный руководитель.
1.8. Требование к документированию
	Проектная документация должна быть разработана в соответствии с ГОСТ 34.201-89.
Отчетные материалы должны включать в себя текстовые материалы (предоставленные в виде бумажной копии и на цифровом носителе в формате MS Word).

**Comment by innocentzy** [comment]
[Документ Microsoft Word.docx](https://github.com/innocentzy/bd-coursework/files/9639690/Microsoft.Word.docx)

**Comment by wldmr-key** [comment]
Очень неплохо, но

> 1.1 Общие сведения.
1.1.1 Полное наименование системы и ее условное обозначение.
Данное техническое задание регулирует разработку системы торговой площадки (биржи), предназначенной для взаимного контакта между перевозчиком и грузовладельцем для согласования перевозки груза.

Нужно так 
> 1.1 Общие сведения.
Данное техническое задание регулирует разработку системы торговой площадки (биржи), предназначенной для взаимного контакта между перевозчиком и грузовладельцем для согласования перевозки груза.
1.1.1 Полное наименование системы и ее условное обозначение.
<<твое название>>

> В настоящее время процессы поиска и сделки происходят следующим образом:

"В настоящее время" - лишнее

> 1.4.1. Требования структуре и функционированию системы.

все что здесь написано - ниачем. Структура системы??? Из чего она состоит? Какие основные функции описанных тобой процессов она охватывает?

> 1.4.6. Требования к составу технических средств.

)) этого будет достаточно и для грузоперевозчиков и для грузовладельцев? ))

**Comment by innocentzy** [comment]
1.1 Общие сведения.
Данное техническое задание регулирует разработку системы торговой площадки (биржи), предназначенной для взаимного контакта между перевозчиком и грузовладельцем для согласования перевозки груза.
1.1.1	Полное наименование системы и ее условное обозначение.
Биржа грузоперевозок “ГрандВэй”

1.4.1. Требования структуре и функционированию системы.
Биржа грузоперевозок должна представлять собой систему, включающую в себя следующие функции: 
- функция создания заявки перевозки груза; 
- функция просмотра и одобрения заявок администратором;
- функция для ответа на полученные заявки для грузоперевозчиков;
- функция уведомлений пользователей о успешной сделки;
- функция оценок и отзывов;
- функция оплаты заказа;
- функция подписок.

1.4.6. Требования к составу технических средств.
− операционная система: Windows 7 и выше
− тактовая частота процессора: не менее 1 ГГц;
− оперативная память: не менее 256 МБ;
− разрешение экрана: не менее 1024×768
− скорость интернет-соединения: 256 Кбайт/с.

**Comment by innocentzy** [comment]
и добавил в сведения о пользователях системы:
•	Администратор
Просмотр, изменение и одобрение заявок и предложений. Доступ к просмотру и изменению баз данных.

**Comment by wldmr-key** [comment]
> Доступ к просмотру и изменению баз данных

pgAdmin ему дашь? Думаю это лишнее

Что значит "изменение"? Цену что ли поменять может? Или номер машины? Желательно функции администрирования чуть подробнее расписать

**Comment by innocentzy** [comment]
• Администратор 
Имеет доступ к панели администратора, в которой может просматривать и удалять завершенные сделки. В эту же панель приходят заявки грузовладельцев для одобрения. Через панель администратор может принять или отклонить заявку на грузоперевозку.

**Comment by innocentzy** [comment]
пока пользователей не так много, да 
потом придется развиваться...

**Comment by wldmr-key** [comment]
ок, пусть будет так
