### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#4]

**Comment by innocentzy** [comment]
Описание предметной области
В качестве предметной области выбрана биржа грузоперевозок “ГрандВэй”, которая предоставляет платформу для связи перевозчиков и грузовладельцев. Информационная система данной биржи позволяет минимизировать риск мошенничества, упростить организацию перевозки и сделать общение между перевозчиком и грузовладельцем более комфортным. 
Процесс сделки перевозчика и грузовладельца начинается с поступления заявки на грузоперевозку от грузовладельца. Затем эта заявка обрабатывается администратором, далее он может одобрить или отклонить заявку. При одобрении заявки она становится доступной для предложений перевозчиков. Грузовладелец получает предложения перевозчиков по своей заявке и выбирает среди них то, которое его устраивает. Перевозчик, чье предложение было выбрано получает уведомление о том, что можно начать выполнять заказ. По выполнении работы грузовладельцу будет предложено оценить работу перевозчика и написать отзыв.
Система создается для обслуживания следующих групп пользователей: грузовладелец; перевозчик; администрация. 
Каждая заявка характеризуется следующими параметрами: место загрузки, место разгрузки, масса груза, дата, цена, способ оплаты. Для ответного предложения: цена, тип транспорта.
О каждом перевозчике хранятся следующие сведения: имя, фотография, стаж вождения, рейтинг, тип транспорта, транспорт, телефон. Для грузовладельцев: имя, телефон.
Для каждой сделки необходимо сохранять номер сделки, данные о грузовладельце, перевозчике, место загрузки и разгрузки и окончательную цену в базу данных.
Пользователи должны иметь возможность получить историю всех завершенных сделок.

**Comment by wldmr-key** [comment]
ок, надеюсь в доке то же, что и в тексте, а то я его и не открывал
