### ISSUE TITLE
Выполнить предварительный анализ аналогов

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#5]

**Comment by innocentzy** [comment]
1. «АвтоТрансИнфо» – популярный сервис, основная задача которого сводится к организации работы рынка грузоперевозок с упором на удобство и эффективность для всех участников.
      Тысячи грузовладельцев находят на площадке АТИ транспорт для транспортировки груза в заданный пункт назначения. Пользователи ресурса бесплатно или за определенную плату размещают информацию о предоставляемых услугах, включая другую информацию, полезную для заказчика.
К преимуществам сервиса АТИ также относятся:
•	Возможность страхования груза;
•	Содействие в оформлении пропуска в Москву;
•	Достоверный рейтинг пользователей ресурсом;
•	Мобильная версия сайта.
Некоторых перевозчиков настораживает большое число посредников, через руки которых проходят заявки. Однако риск того, что пользователь останется без прибыли, фактически равна нулю. Стоит также отметить, что бесплатные опции на сайте ограничены: дополнительные функции входят в категорию платных услуг.
 
Рисунок 1. Начальная страница сайта «АвтоТрансИнфо»
2. Автодиспетчер – это информационный ресурс, который способен обеспечить быстрые и качественные услуги на рынке грузоперевозок. 
Он представлен в виде базы данных – каждый день на сайт поступает информация о свободном транспорте, а также количестве груза для перевозки. Это позволяет наладить контакт между всеми участниками процесса, включая перевозчиков, грузовладельцев, автодиспетчеров и экспедиторов.
Компания предлагает пользователям следующие виды услуг:
•	процедура размещения груза и транспорта – бесплатно;
•	доступ к личным данным перевозчиков или владельцев груза – бесплатно;
•	рассылка в виде СМС о наличии груза и транспорта – платно;
•	размещение рекламного объявления на верхней позиции с выделением – платно.
Автодиспетчер работает на рынке с 2009 года. В течение этих лет его главной целью является обеспечение быстрой и надежной перевозки груза из одного объекта в другой. Компания принимает в учет сложившуюся финансовую ситуацию и охватывает максимальный набор услуг для того, чтобы клиент мог обратиться с любым вопросом. Она выработала собственный подход к решению задач, идет навстречу клиентам, предлагает различные формы сотрудничества с учетом требований конкретно взятого заказчика.
 
Рисунок 2. Начальная страница сайта «Автодиспетчер»
3. Cargomart осуществляет деятельность в сфере транспортной логистики. Платформа оформлена в виде электронной базы и предназначена для согласования условий поездки между всеми участниками процесса. Она работает с перевозчиками и грузовладельцами. В качестве перевозчиков может выступать диспетчер или транспортная фирма, в качестве грузовладельца – резидент, физическое лицо, представитель малого или крупного бизнеса.
Cargomart предлагает своим пользователям:
•	Владельцу груза – большой выбор транспортных компаний (более 1 тыс.), на учете которых состоит 16 тыс. различных грузовых машин.
•	Перевозчику – ежемесячное оформление около 7 тыс. прямых заказов из 150 населенных пунктов по всей территории России.
Cargomart предлагает удобный функционал для пользователей:
•	в комментариях к заказу указывает только актуальная информация, что позволяет избежать информационного «мусора»;
•	перед оформлением записи можно указать предварительные пункты погрузки и выгрузки продукции из всего маршрута;
•	здесь же прописывается дополнительная информация: требования к оборудованию или необходимость медицинской книжки;
•	в разделе «Условия оплаты» согласовываются сроки и сумма денежных средств, подлежащая к перечислению за услуги.
 
Рисунок 3. Начальная страница сайта «Gargomart»

**Comment by innocentzy** [comment]
[analogi.docx](https://github.com/innocentzy/bd-coursework/files/9713698/analogi.docx)

**Comment by wldmr-key** [comment]
все неплохо, но желательно изучитьмнение пользователей этих систем
И необходимо сделать свои выводы - что ты из опыта аналогов воспринимаешь для проектируемой системы. Как она будет соотноситься с аналогами
