### ISSUE TITLE
Создать концептуальную схему данных предметной области

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#6]

**Comment by innocentzy** [comment]
[bd.pdf](https://github.com/innocentzy/bd-coursework/files/9846999/bd.pdf)

**Comment by wldmr-key** [comment]
хоть я и одобрил в общем твое описание предметной области, на концептуальной схеме сразу видны недостаток глубины ее изучения

Что такое сущность "груз"? 2 кубометра досок?
Грузоподъемность и оснащенность авто не имеет значения
Сроки доставки?
и еще полно вопросов

стоит обсудить на консультации

**Comment by innocentzy** [comment]
[bd.pdf](https://github.com/innocentzy/bd-coursework/files/10086268/bd.pdf)

**Comment by wldmr-key** [comment]
что за жуткие названия для сущностей? Если у тебя эксперт по предметной области понимает только английский, то почему названия атрибутов на русском?
Как report соотносится с твоим описанием предметной области?
Что за Id?

оть я и одобрил в общем твое описание предметной области, на концептуальной схеме сразу видны недостаток глубины ее изучения

Что такое сущность "груз"? 2 кубометра досок?
Грузоподъемность и оснащенность авто не имеет значения
Сроки доставки?
и еще полно вопросов

стоит обсудить на консультации

**Comment by innocentzy** [comment]
![bd](https://user-images.githubusercontent.com/52624927/226184719-e82deb34-3d3c-466c-bbe7-282d67444edc.png)

**Comment by innocentzy** [comment]
![bd copy](https://user-images.githubusercontent.com/52624927/227618353-bb46847e-5c04-46e0-8ba3-242169e0a575.png)

**Comment by innocentzy** [comment]
![bd copy](https://user-images.githubusercontent.com/52624927/227618559-23f4ec16-7916-4633-ac44-dbd31e5566f2.png)

**Comment by innocentzy** [comment]
![123](https://user-images.githubusercontent.com/52624927/227621506-b830789e-5b2d-4510-87fc-aad73082e205.png)

**Comment by wldmr-key** [comment]
заявка у тебя атрибут ответа или сущность? Что она у тебя дедает в ответе? Ты будешь отвечать на вопросы?

Что такое сущность "груз"? 2 кубометра досок?
Грузоподъемность и оснащенность авто не имеет значения

Или это у тебя есть в описании предметной области и я плохо читал:

**Comment by innocentzy** [comment]
![123](https://user-images.githubusercontent.com/52624927/227880735-3f242158-990e-4e03-902e-9ac5589c6640.png)

**Comment by innocentzy** [comment]
![123](https://user-images.githubusercontent.com/52624927/227881884-bfdbe038-33e6-4b8c-bf02-858bb481386e.png)

**Comment by wldmr-key** [comment]
блин! тебе все разжевать надо?! Создатель ответа - это атрибут или сущность?

**Comment by innocentzy** [comment]
![123](https://user-images.githubusercontent.com/52624927/228050661-50cd5945-2e04-4533-9c4a-d04b5f933df2.png)

**Comment by wldmr-key** [comment]
так если это сущности, то почему они у тебя дублируются в атрибутах? куда связь между заявкой и ответами дел в последнем варианте?

**Comment by innocentzy** [comment]
![123](https://user-images.githubusercontent.com/52624927/228071552-df63a376-54bd-4087-874b-9d3adafa114b.png)

**Comment by innocentzy** [comment]
![123](https://user-images.githubusercontent.com/52624927/228779022-472ce54b-316a-4a9b-8f3d-191087341dd5.png)

**Comment by wldmr-key** [comment]
норм
