### ISSUE TITLE
Изготовить прототип или скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by innocentzy** [innocentzy/bd-coursework#7]

**Comment by innocentzy** [comment]
[cursework.pdf](https://github.com/innocentzy/bd-coursework/files/9846937/cursework.pdf)

**Comment by wldmr-key** [comment]
скетчи дают представление о количестве экранов, но малоинформативны с точки зрения их содержания. Чем скажем характеризуются заказы?

**Comment by innocentzy** [comment]
[interface.pdf](https://github.com/innocentzy/bd-coursework/files/11011323/interface.pdf)
